root = "."
tmp_dir = "tmp"

[build]
pre_cmd = [""]
bin = "true"
cmd = "echo 'running proxy one' && templ generate --notify-proxy --proxybind='localhost' --proxyport='8080'"
include_dir = ["assets"]
include_ext = [""]
include_file = ["js,css"]
exclude_file = []
exclude_regex = ["_test\\.go", "_templ\\.go"]
exclude_unchanged = false
follow_symlink = false
log = "build-errors-air.log"
full_bin = ""
delay = 100
poll = false
rerun = false
rerun_delay = 500
poll_interval = 500
kill_delay = "0s"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true