root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["bun run fmt "]
bin = "./tmp/main"
cmd = "templ generate && go build -o ./tmp/main ./main.go"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
exclude_dir = ["bin", "dist","assets", "tmp", "vendor", "node_modules", "bin","tests", "vendor"]
exclude_file = []
exclude_regex = ["_test\\.go", "_templ\\.go"]
exclude_unchanged = false
follow_symlink = false
log = "build-errors-air.log"
full_bin = ""
delay = 1000
poll = false
poll_interval = 500
kill_delay = "0s"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true